CXX = g++ # the lab requires g++, not gcc
CXXFLAGS = -Wall -Wextra -std=c++17
main: matrix.cpp # target: what it depends on
	$(CXX) $(CXXFLAGS) matrix.cpp -o MatrixLab5
clean:
	rm -f MatrixLab5
.PHONY: clean
